[common]
;0001 : enable debug
;0002 : disable raspberry hardware code, to debug other code in pc
Debug=0
SerialNumber=0
DeviceName=HomeAssistantDemo
DeviceID=hademo

[broker]
;Immoto
;host=127.0.0.1

;HomeAssistant
host=192.168.1.99
port=1883
id=
user=mqttuser
pass=zanzara
ssl=0
